-- Add global question support so every user sees the shared AWSify library
ALTER TABLE public.mcq_questions
  ADD COLUMN IF NOT EXISTS is_global boolean NOT NULL DEFAULT false;

-- Allow global questions to set user_id to NULL while keeping a default for user inserts
ALTER TABLE public.mcq_questions
  ALTER COLUMN user_id DROP NOT NULL;

ALTER TABLE public.mcq_questions
  ALTER COLUMN user_id SET DEFAULT auth.uid();

-- Ensure existing rows have the new column set to false explicitly
UPDATE public.mcq_questions
SET is_global = false
WHERE is_global IS NULL;

-- Refresh row level security policies to account for global visibility
DROP POLICY IF EXISTS "Users can view own questions" ON public.mcq_questions;
DROP POLICY IF EXISTS "Users can insert own questions" ON public.mcq_questions;
DROP POLICY IF EXISTS "Users can update own questions" ON public.mcq_questions;
DROP POLICY IF EXISTS "Users can delete own questions" ON public.mcq_questions;

CREATE POLICY "Users can view personal or global questions"
ON public.mcq_questions
FOR SELECT
USING (auth.uid() = user_id OR is_global = true);

CREATE POLICY "Users can insert personal questions"
ON public.mcq_questions
FOR INSERT
WITH CHECK (auth.uid() = user_id AND is_global = false);

CREATE POLICY "Users can update personal questions"
ON public.mcq_questions
FOR UPDATE
USING (auth.uid() = user_id AND is_global = false)
WITH CHECK (auth.uid() = user_id AND is_global = false);

CREATE POLICY "Users can delete personal questions"
ON public.mcq_questions
FOR DELETE
USING (auth.uid() = user_id AND is_global = false);

-- Seed the shared AWSify question library (dedupe on question text to avoid double inserts)
WITH seed_data AS (
  SELECT * FROM json_to_recordset($$[
    {"service_name":"AWS Well-Architected Framework","question":"Which pillar of the AWS Well-Architected Framework focuses on continually improving processes and procedures?","options":["Security Pillar","Reliability Pillar","Operational Excellence Pillar","Cost Optimization Pillar"],"correct_answer":"Operational Excellence Pillar","category":"Well-Architected Framework","difficulty":"easy","explanation":"The Operational Excellence Pillar focuses on running and monitoring systems to deliver business value, and continually improving processes and procedures."},
    {"service_name":"AWS Well-Architected Framework","question":"To ensure your AWS infrastructure adheres to best practices for protecting data and systems, which pillar of the AWS Well-Architected Framework should you primarily focus on?","options":["Performance Efficiency Pillar","Security Pillar","Reliability Pillar","Sustainability Pillar"],"correct_answer":"Security Pillar","category":"Well-Architected Framework","difficulty":"easy","explanation":"The Security Pillar focuses on protecting information, systems, and assets while delivering business value through risk assessments and mitigation strategies."},
    {"service_name":"AWS Well-Architected Framework","question":"Which pillar of the AWS Well-Architected Framework emphasizes the ability of a system to recover from infrastructure or service disruptions?","options":["Operational Excellence Pillar","Performance Efficiency Pillar","Reliability Pillar","Cost Optimization Pillar"],"correct_answer":"Reliability Pillar","category":"Well-Architected Framework","difficulty":"easy","explanation":"The Reliability Pillar focuses on the ability of a system to recover from infrastructure or service disruptions, dynamically acquire computing resources to meet demand, and mitigate disruptions such as misconfigurations or transient network issues."},
    {"service_name":"AWS Well-Architected Framework","question":"When designing your AWS architecture, optimizing for the efficient use of computing resources and maintaining efficiency as demand changes falls under which pillar?","options":["Security Pillar","Reliability Pillar","Performance Efficiency Pillar","Cost Optimization Pillar"],"correct_answer":"Performance Efficiency Pillar","category":"Well-Architected Framework","difficulty":"medium","explanation":"The Performance Efficiency Pillar focuses on using computing resources efficiently to meet system requirements, and maintaining that efficiency as demand changes and technologies evolve."},
    {"service_name":"AWS Well-Architected Framework","question":"To avoid unnecessary expenses and achieve maximum business value, which AWS Well-Architected Pillar is most relevant?","options":["Operational Excellence Pillar","Performance Efficiency Pillar","Reliability Pillar","Cost Optimization Pillar"],"correct_answer":"Cost Optimization Pillar","category":"Well-Architected Framework","difficulty":"easy","explanation":"The Cost Optimization Pillar focuses on avoiding unneeded costs by managing resources, selecting appropriate services, and analyzing spending patterns."},
    {"service_name":"AWS Well-Architected Framework","question":"Which of the following is a newly added pillar to the AWS Well-Architected Framework, focusing on minimizing environmental impacts?","options":["Governance Pillar","Compliance Pillar","Sustainability Pillar","Resilience Pillar"],"correct_answer":"Sustainability Pillar","category":"Well-Architected Framework","difficulty":"easy","explanation":"The Sustainability Pillar focuses on minimizing the environmental impacts of running cloud workloads, including energy consumption and resource utilization."},
    {"service_name":"AWS Well-Architected Tool","question":"What is the primary purpose of the AWS Well-Architected Tool?","options":["To automatically deploy AWS infrastructure.","To perform security audits on AWS accounts.","To review workloads against the AWS Well-Architected Framework best practices.","To calculate the cost of AWS services."],"correct_answer":"To review workloads against the AWS Well-Architected Framework best practices.","category":"Well-Architected Tool","difficulty":"medium","explanation":"The AWS Well-Architected Tool helps you review the state of your workloads and compares them to the latest AWS architectural best practices."},
    {"service_name":"Infrastructure as Code","question":"What is the main benefit of implementing Infrastructure as Code (IaC)?","options":["It eliminates the need for any manual configuration.","It provides a way to manage infrastructure in a declarative manner.","It automatically optimizes resource utilization for cost savings.","It encrypts all data at rest by default."],"correct_answer":"It provides a way to manage infrastructure in a declarative manner.","category":"Cloud Concepts","difficulty":"easy","explanation":"Infrastructure as Code (IaC) allows you to manage and provision computing infrastructure through machine-readable definition files, rather than physical hardware configuration or interactive configuration tools."},
    {"service_name":"AWS Global Infrastructure","question":"What are AWS Regions primarily designed for?","options":["To host individual AWS services.","To provide a single global point of access for all AWS services.","To allow customers to choose the optimal geographic location for their services to meet latency and compliance requirements.","To provide direct network connections to customer data centers."],"correct_answer":"To allow customers to choose the optimal geographic location for their services to meet latency and compliance requirements.","category":"AWS Global Infrastructure","difficulty":"easy","explanation":"AWS Regions are physical locations around the world where AWS clusters data centers, allowing customers to choose a geographic region to host their services for latency, compliance, and proximity needs."},
    {"service_name":"AWS Local Zones","question":"What is the primary use case for AWS Local Zones?","options":["To expand global reach with full AWS Region capabilities.","To run latency-sensitive applications closer to end-users and on-premises installations.","To provide dedicated network connections to AWS Regions.","To offer disaster recovery for existing AWS Regions."],"correct_answer":"To run latency-sensitive applications closer to end-users and on-premises installations.","category":"AWS Global Infrastructure","difficulty":"medium","explanation":"AWS Local Zones are a type of AWS infrastructure deployment that places compute, storage, database, and other select services closer to large population, industry, and IT centers, enabling very low latency to end-users or local on-premises installations."},
    {"service_name":"AWS Points of Presence (PoPs)","question":"Which AWS Global Infrastructure component is primarily associated with Amazon CloudFront and AWS Global Accelerator?","options":["Regions","Availability Zones","Local Zones","Points of Presence (Edge Locations)"],"correct_answer":"Points of Presence (Edge Locations)","category":"AWS Global Infrastructure","difficulty":"medium","explanation":"Points of Presence (PoPs) or Edge Locations are used by services like Amazon CloudFront and AWS Global Accelerator to deliver content with low latency and improve application performance by terminating network connections close to users."},
    {"service_name":"AWS Identity and Access Management (IAM)","question":"Which security best practice in IAM involves granting only the necessary permissions for users, roles, or services to perform their tasks?","options":["Using strong passwords","Rotating access keys regularly","Applying Least-Privilege Permissions","Enabling MFA"],"correct_answer":"Applying Least-Privilege Permissions","category":"Security (IAM)","difficulty":"easy","explanation":"Least privilege is an IAM security best practice that recommends granting only the permissions required to perform a task, preventing unintended actions or access."},
    {"service_name":"AWS Identity and Access Management (IAM)","question":"What is the most secure way to store AWS security credentials for programmatic access to AWS services?","options":["Hardcode them directly in application code.","Store them in plain text files on a local machine.","Use IAM roles for EC2 instances or other AWS services.","Email them to team members."],"correct_answer":"Use IAM roles for EC2 instances or other AWS services.","category":"Security (IAM)","difficulty":"medium","explanation":"IAM roles provide temporary credentials and are the most secure way to grant permissions to applications running on EC2 or other AWS services, eliminating the need to embed static credentials."},
    {"service_name":"AWS IAM Identity Center","question":"What is the primary benefit of using AWS IAM Identity Center (formerly AWS SSO)?","options":["To enforce least privilege access to a single AWS account.","To centralize access management to multiple AWS accounts and business applications.","To create custom IAM policies for specific resources.","To test IAM policies before deploying them."],"correct_answer":"To centralize access management to multiple AWS accounts and business applications.","category":"Security (IAM)","difficulty":"medium","explanation":"IAM Identity Center helps you centrally manage single sign-on (SSO) access to multiple AWS accounts and business applications, and provides users with a portal to access all their assigned applications."},
    {"service_name":"AWS Identity and Access Management (IAM)","question":"Which tool would you use to verify the effective permissions of an IAM policy before attaching it to a user or role?","options":["AWS CloudTrail","AWS Config","IAM Policy Simulator","AWS Security Hub"],"correct_answer":"IAM Policy Simulator","category":"Security (IAM)","difficulty":"medium","explanation":"The IAM Policy Simulator allows you to test the effects of IAM policies, helping you understand what actions a user or role can perform on which resources before deploying the policy."},
    {"service_name":"AWS Identity and Access Management (IAM)","question":"What is the fundamental difference between an identity-based policy and a resource-based policy?","options":["Identity-based policies define who can access a resource, while resource-based policies define what actions are allowed on the resource by specific principals.","Identity-based policies are always attached to users, while resource-based policies are always attached to roles.","Identity-based policies define permissions on all resources in an account, while resource-based policies define permissions only for a single resource.","Identity-based policies are for AWS services, resource-based policies are for human users."],"correct_answer":"Identity-based policies define who can access a resource, while resource-based policies define what actions are allowed on the resource by specific principals.","category":"Security (IAM)","difficulty":"hard","explanation":"Identity-based policies (attached to users, groups, roles) specify what that identity can do. Resource-based policies (attached to a resource like an S3 bucket or SQS queue) specify who (principals) can access that specific resource and what actions they can perform."},
    {"service_name":"Amazon Simple Storage Service (S3)","question":"Which of the following is NOT a primary feature of Amazon S3?","options":["Object storage for static files.","File system access for operating systems.","High durability and availability.","Scalability for virtually unlimited data."],"correct_answer":"File system access for operating systems.","category":"Storage (S3)","difficulty":"easy","explanation":"Amazon S3 is an object storage service, not a traditional file system. Services like Amazon EFS or FSx provide file system access."},
    {"service_name":"Amazon S3","question":"What is the recommended method for uploading large objects (over 100 MB) to Amazon S3 to improve transfer speed and reliability?","options":["Using the `PutObject` API with a single request.","Using Amazon S3 Transfer Acceleration.","Using Multipart Upload.","Compressing the object before uploading."],"correct_answer":"Using Multipart Upload.","category":"Storage (S3)","difficulty":"medium","explanation":"Multipart Upload allows you to upload a single object as a set of parts. It can improve throughput by uploading parts in parallel and offers quick recovery from network issues by retrying only failed parts."},
    {"service_name":"Amazon S3 Transfer Acceleration","question":"What is the main benefit of using Amazon S3 Transfer Acceleration?","options":["Reduces S3 storage costs.","Accelerates data transfers to and from S3 buckets over long distances.","Automatically encrypts S3 objects.","Provides strong consistency for S3 operations."],"correct_answer":"Accelerates data transfers to and from S3 buckets over long distances.","category":"Storage (S3)","difficulty":"medium","explanation":"S3 Transfer Acceleration speeds up content transfers to and from S3 buckets over long distances by using CloudFront's globally distributed edge locations."},
    {"service_name":"AWS Transfer Family","question":"Which AWS service allows you to easily and securely transfer files over SFTP, FTPS, and FTP into and out of Amazon S3 or Amazon EFS?","options":["AWS Storage Gateway","Amazon S3 Glacier","AWS Transfer Family","Amazon S3 File Gateway"],"correct_answer":"AWS Transfer Family","category":"Storage (S3)","difficulty":"medium","explanation":"AWS Transfer Family provides fully managed support for file transfers directly into and out of Amazon S3 or Amazon EFS using SFTP, FTPS, and FTP."},
    {"service_name":"Amazon S3 Storage Classes","question":"For objects that are accessed infrequently but require rapid access when needed, and you want to minimize storage costs, which S3 storage class would be most appropriate?","options":["S3 Standard","S3 Intelligent-Tiering","S3 Glacier Deep Archive","S3 Standard-IA"],"correct_answer":"S3 Standard-IA","category":"Storage (S3)","difficulty":"medium","explanation":"Amazon S3 Standard-Infrequent Access (S3 Standard-IA) is for data that is accessed less frequently, but requires rapid access when needed. It offers lower storage price than S3 Standard but a retrieval fee."},
    {"service_name":"Amazon S3","question":"What is the primary benefit of enabling Versioning on an S3 bucket?","options":["To reduce storage costs for old object versions.","To enable cross-region replication automatically.","To protect against accidental deletions and overwrites.","To accelerate data transfer to the bucket."],"correct_answer":"To protect against accidental deletions and overwrites.","category":"Storage (S3)","difficulty":"easy","explanation":"S3 Versioning keeps multiple versions of an object in the same bucket, protecting against unintended overwrites, deletions, and allowing for easy recovery of previous versions."},
    {"service_name":"Amazon S3","question":"Your web application hosted on an EC2 instance needs to access objects in an S3 bucket. To allow web browsers to securely load resources from the S3 bucket when the web app is served from a different domain, what S3 feature must be configured?","options":["S3 Bucket Policies","S3 Access Control Lists (ACLs)","Cross-Origin Resource Sharing (CORS)","S3 Block Public Access"],"correct_answer":"Cross-Origin Resource Sharing (CORS)","category":"Storage (S3)","difficulty":"hard","explanation":"CORS (Cross-Origin Resource Sharing) is a browser security feature that restricts web pages from making requests to a different domain than the one that served the web page. You must configure CORS on your S3 bucket to allow web browsers to access its content from a different origin."},
    {"service_name":"Amazon S3","question":"Amazon S3 offers strong read-after-write consistency for PUTs of new objects and eventual consistency for overwrite PUTs and DELETEs. Which consistency model ensures that if you read an object immediately after writing it, you will always get the latest version?","options":["Eventual Consistency","Read-After-Write Consistency","Strong Consistency","Weak Consistency"],"correct_answer":"Strong Consistency","category":"Storage (S3)","difficulty":"medium","explanation":"Amazon S3 offers strong read-after-write consistency for PUTs of new objects and for overwrite PUTs and DELETEs in all AWS Regions. This means that after a successful write, any subsequent read request will immediately retrieve the latest version of the object."},
    {"service_name":"Amazon S3","question":"Which S3 feature can you use to get a daily report that lists all of your objects and their corresponding metadata for an S3 bucket?","options":["S3 Event Notifications","S3 Analytics","S3 Replication","S3 Inventory"],"correct_answer":"S3 Inventory","category":"Storage (S3)","difficulty":"medium","explanation":"Amazon S3 Inventory provides a flat file list of your objects and their corresponding metadata on a daily or weekly basis for an S3 bucket or a shared prefix."},
    {"service_name":"Amazon EC2","question":"What is an Amazon Machine Image (AMI) primarily used for?","options":["To provide block storage for EC2 instances.","To create a template for launching EC2 instances.","To define networking rules for EC2 instances.","To monitor the performance of EC2 instances."],"correct_answer":"To create a template for launching EC2 instances.","category":"Compute (EC2)","difficulty":"easy","explanation":"An AMI (Amazon Machine Image) provides the information required to launch an EC2 instance, acting as a template for the root volume of the instance."},
    {"service_name":"Amazon EC2","question":"What is the purpose of an EC2 Instance Type?","options":["To define the operating system for the instance.","To determine the hardware configuration (CPU, memory, storage) of an instance.","To specify the network security groups for an instance.","To set the pricing model for an instance."],"correct_answer":"To determine the hardware configuration (CPU, memory, storage) of an instance.","category":"Compute (EC2)","difficulty":"easy","explanation":"An instance type defines the optimal combination of CPU, memory, storage, and networking capacity for various workloads."},
    {"service_name":"AWS Compute Optimizer","question":"To get recommendations on optimal AWS resources for your workloads to reduce costs and improve performance, which service should you use?","options":["AWS Cost Explorer","AWS Trusted Advisor","AWS Compute Optimizer","Amazon CloudWatch"],"correct_answer":"AWS Compute Optimizer","category":"Compute (EC2)","difficulty":"medium","explanation":"AWS Compute Optimizer recommends optimal AWS resources for your workloads to reduce costs and improve performance by using machine learning to analyze historical utilization metrics."},
    {"service_name":"Amazon EC2","question":"You need to execute commands on an EC2 Linux instance immediately after it launches. Which feature would you use?","options":["AWS Systems Manager Run Command","EC2 User Data","EC2 Instance Connect","AWS CloudFormation Init"],"correct_answer":"EC2 User Data","category":"Compute (EC2)","difficulty":"medium","explanation":"User data is commands that are supplied to a launched instance. These commands run during the first boot cycle and allow for automating configuration tasks, such as installing software, mounting file systems, or starting services."},
    {"service_name":"Amazon EBS","question":"Which type of storage provides persistent block-level storage volumes for use with Amazon EC2 instances?","options":["Amazon S3","Amazon EFS","Amazon EBS","EC2 Instance Store"],"correct_answer":"Amazon EBS","category":"Storage (EBS)","difficulty":"easy","explanation":"Amazon Elastic Block Store (EBS) provides persistent block storage volumes for EC2 instances, meaning data persists even if the instance is stopped or terminated."},
    {"service_name":"Amazon EC2 Instance Store","question":"What characteristic describes EC2 Instance Store volumes?","options":["They are persistent and can be detached and reattached to other instances.","They provide high-performance temporary block storage that is physically attached to the host computer.","They are automatically backed up to Amazon S3.","They are designed for shared access across multiple EC2 instances."],"correct_answer":"They provide high-performance temporary block storage that is physically attached to the host computer.","category":"Storage (EC2)","difficulty":"medium","explanation":"An instance store provides temporary block-level storage for your instance. This storage is located on disks that are physically attached to the host computer."},
    {"service_name":"Amazon Elastic File System (EFS)","question":"For a Linux-based application running on multiple EC2 instances that needs a shared, scalable file system, which AWS service is the most appropriate choice?","options":["Amazon S3","Amazon EBS","Amazon EFS","Amazon FSx for Windows File Server"],"correct_answer":"Amazon EFS","category":"Storage (EFS)","difficulty":"easy","explanation":"Amazon EFS provides a scalable, elastic, cloud-native NFS file system for Linux EC2 instances, allowing multiple instances to access the same file system concurrently."},
    {"service_name":"Amazon FSx for Windows File Server","question":"Your EC2 instances are running Windows applications that require shared file storage with full Windows file system compatibility and SMB protocol support. Which AWS service would you use?","options":["Amazon EFS","Amazon S3","Amazon EBS","Amazon FSx for Windows File Server"],"correct_answer":"Amazon FSx for Windows File Server","category":"Storage (FSx)","difficulty":"medium","explanation":"Amazon FSx for Windows File Server provides a fully managed, highly reliable, and scalable file storage that's accessible via the Server Message Block (SMB) protocol, with full Windows file system compatibility."},
    {"service_name":"Amazon DynamoDB","question":"Which statement best describes Amazon DynamoDB?","options":["A managed relational database service.","A fully managed NoSQL key-value and document database service.","A data warehousing service for analytics.","A distributed file system for big data."],"correct_answer":"A fully managed NoSQL key-value and document database service.","category":"Database (DynamoDB)","difficulty":"easy","explanation":"Amazon DynamoDB is a fast and flexible NoSQL database service for all applications that need consistent, single-digit millisecond latency at any scale."},
    {"service_name":"Amazon DynamoDB","question":"What is a core component of Amazon DynamoDB that represents a collection of items?","options":["Table","Bucket","Volume","Instance"],"correct_answer":"Table","category":"Database (DynamoDB)","difficulty":"easy","explanation":"In DynamoDB, data is stored in tables, which are collections of items. Each item is a collection of attributes."},
    {"service_name":"Amazon Virtual Private Cloud (VPC)","question":"What does CIDR (Classless Inter-Domain Routing) notation help define within an Amazon VPC?","options":["The number of EC2 instances allowed in a subnet.","The size and range of IP addresses for a VPC or subnet.","The encryption standard for data in transit.","The maximum data transfer rate for an EC2 instance."],"correct_answer":"The size and range of IP addresses for a VPC or subnet.","category":"Networking (VPC)","difficulty":"medium","explanation":"CIDR notation is used to specify IP address ranges for your VPCs and subnets, determining the number of available IP addresses within that range."},
    {"service_name":"AWS PrivateLink","question":"What is the primary benefit of using AWS PrivateLink?","options":["To allow public internet access to your private services.","To provide private connectivity between VPCs and AWS services without exposing traffic to the public internet.","To accelerate internet-facing applications globally.","To establish a dedicated network connection from on-premises to AWS."],"correct_answer":"To provide private connectivity between VPCs and AWS services without exposing traffic to the public internet.","category":"Networking","difficulty":"medium","explanation":"AWS PrivateLink enables you to establish private connectivity between VPCs and AWS services, or on-premises applications, securely and directly without traversing the public internet."},
    {"service_name":"AWS Transit Gateway","question":"To connect thousands of Amazon VPCs and on-premises networks through a central hub, simplifying network management, which AWS service would you use?","options":["AWS Direct Connect","AWS VPN","AWS Transit Gateway","Amazon VPC Peering"],"correct_answer":"AWS Transit Gateway","category":"Networking","difficulty":"medium","explanation":"AWS Transit Gateway connects your Amazon VPCs and on-premises networks through a central hub, simplifying your network architecture."},
    {"service_name":"AWS Global Accelerator","question":"What is the primary function of AWS Global Accelerator?","options":["To provide a content delivery network for static and dynamic content.","To improve the availability and performance of your applications by directing traffic to optimal AWS endpoints globally.","To establish a private connection from your data center to AWS.","To load balance traffic across multiple EC2 instances in a single region."],"correct_answer":"To improve the availability and performance of your applications by directing traffic to optimal AWS endpoints globally.","category":"Networking","difficulty":"medium","explanation":"AWS Global Accelerator improves the availability and performance of your applications with a single entry point to global AWS network infrastructure, directing user traffic to the closest healthy endpoint."},
    {"service_name":"AWS Direct Connect","question":"When you need a dedicated, private network connection from your on-premises data center directly to AWS, bypassing the public internet, which service should you utilize?","options":["AWS VPN","AWS Direct Connect","AWS Global Accelerator","Amazon VPC"],"correct_answer":"AWS Direct Connect","category":"Networking","difficulty":"easy","explanation":"AWS Direct Connect establishes a dedicated network connection between your premises and AWS, which can reduce network costs, increase bandwidth throughput, and provide a more consistent network experience than Internet-based connections."}
  ]$$)
  AS sd(
    service_name text,
    question text,
    options text[],
    correct_answer text,
    category text,
    difficulty text,
    explanation text
  )
)
INSERT INTO public.mcq_questions (
  service_name,
  question,
  options,
  correct_answer,
  category,
  difficulty,
  explanation,
  is_global,
  user_id
)
SELECT
  sd.service_name,
  sd.question,
  sd.options,
  sd.correct_answer,
  sd.category,
  sd.difficulty,
  sd.explanation,
  true,
  NULL
FROM seed_data sd
WHERE NOT EXISTS (
  SELECT 1 FROM public.mcq_questions existing
  WHERE existing.question = sd.question AND existing.is_global = true
);
